<?php return array (
  'site_title' => 'LensQueen',
  'base_color' => '#d35400',
  'time_zone' => 'Asia/Dhaka',
  'currency' => 'BDT',
  'currency_symbol' => '৳',
  'theme' => 'darkmode',
  'fraction_number' => 2,
  'paginate' => 10,
  'email_verification' => 0,
  'email_notification' => 0,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'sender_email' => 'support@domain.com',
  'sender_email_name' => 'Lens Queen',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'smtp.mailtrap.io',
    'smtp_port' => '465',
    'smtp_encryption' => 'ssl',
    'smtp_username' => 'support@domain.com',
    'smtp_password' => 'a81e905777eb3a',
  ),
  'push_notification' => 0,
  'error_log' => 1,
  'strong_password' => 0,
  'registration' => 0,
  'maintenance' => 0,
  'is_active_cron_notification' => 1,
);