<?php

return [
    "Home",
    "About Us",
    "Services",
    "Blog",
    "Gallery",
    "Shop",
    "Contact",
    "Sign In",
    "My Profile",
    "Dashboard",
    "Logout",
    "Book Now",
    "Confirm Password",
    "Please confirm your password before continuing.",
    "Password",
    "Forgot Your Password?",
    "Reset Password",
    "Forget Your Password?",
    "Enter your email address to reset your password",
    "Send Password Reset Link",
    "Already have an account?",
    "Sign in",
    "New Password",
    "Don't have any account? Sign Up",
    "Email Verification",
    "SMS Verification",
    "2FA Code",
    "Code",
    "Submit",
    "Didn't get Code? Click to",
    "Resend code",
    "Login",
    "Username Or Email Address",
    "Remember Me",
    "Don't have an account?",
    "Sign up",
    "Register",
    "Sign Up",
    "First Name",
    "Last Name",
    "Username",
    "Email Address",
    "Your Phone Number",
    "Phone Number",
    "Preferred language",
    "Select Language",
    "Address",
    "Update User",
    "Current Password",
    "Update Password",
    "Create Account",
    "Email Verify",
    "Verify Your Email Address",
    "A fresh verification link has been sent to your email address.",
    "Before proceeding, please check your email for a verification link.",
    "If you did not receive the email",
    "click here to request another",
    "403 Forbidden",
    "403",
    "You don’t have permission to access ‘/’ on this server.",
    "Back To Home",
    "404",
    "Page Not Found",
    "We're sorry, the page you requested could not be found. Please go back to the homepage or contact us at",
    "opps",
    "405",
    "Method not allowed",
    "opps!",
    "419",
    "Session has been expired",
    "500",
    "Internal Server Error",
    "The server encountered an internal error misconfiguration and was unable to complate your request. Please contact the server administrator.",
    "homepage",
    "Copyright",
    "All Rights Reserved",
    "Or Login With",
    "hero image top",
    "hero image bottom",
    "Previous",
    "Next",
    "Profile Image",
    "Set up all necessary info",
    "2FA Security",
    "Clear",
    "You have no notifications",
    "Dashboard Icon",
    "MyPlans Icon",
    "My Plans",
    "myProducts Icon",
    "Purchased Item",
    "Wishlist Icon",
    "Wishlist",
    "myBooking Icon",
    "My Booking",
    "Payment Icon",
    "Payment History",
    "Profile Settings Icon",
    "Profile Settings",
    "Support Ticket Icon",
    "Support Ticket",
    "about image",
    "Read more",
    "blog image",
    "Read More",
    "All",
    "gallery image",
    "See more",
    "instagram's photo one",
    "instagram's photo two",
    "instagram's photo three",
    "instagram's photo four",
    "Session Features",
    "Purchase Plan",
    "Purchase Now",
    "Price",
    "service image",
    "team member image",
    "testimonial image",
    "image",
    "Booking Form",
    "Information For Plan Confirmation",
    "Booking form image",
    "Select",
    "Change",
    "Remove",
    "Confirm Now",
    "My Bookings",
    "SL No.",
    "Date",
    "Status",
    "Action",
    "Pending",
    "Rejected",
    "Approved",
    "Details",
    "No Data Found!",
    "Booking Request Form",
    "Additional Information To Plan Confirm",
    "My Booking Request Form",
    "Additional Information",
    "Plan Name",
    "Purchased At",
    "My Products",
    "Product Name",
    "Download",
    "Your Card Information",
    "card image",
    "Enter your card number",
    "Enter the name on your card",
    "Warning",
    "Add Fund",
    "Uh-ho! We are unable to process your Payment by this method.",
    "This method is under construction!!",
    "bkash",
    "as your payment method.",
    "Payment Preview",
    "PLEASE SEND EXACTLY",
    "crypto payment image",
    "SCAN TO SEND",
    "flutterwave payment image",
    "Please Pay",
    "To Get",
    "Pay Now",
    "marcado payment image",
    "monnify payment image",
    "razorpay payment image",
    "stripe payment image",
    "voguepay payment image",
    "Pay via Monnify",
    "Pay with VoguePay",
    "Pay with",
    "Choose Image",
    "Joined At",
    "Image Update",
    "Profile Information",
    "Password Setting",
    "Payment Confirm",
    "Update",
    "Keywords",
    "Payment Logs",
    "Payment Pending",
    "Search Payment Logs",
    "Subscriber Manager",
    "Send Email to Subscribers",
    "New Ticket",
    "Ticket: #",
    "Enter Subject",
    "Subject",
    "Message",
    "Upload File",
    "Create Ticket",
    "Last Reply",
    "Ticket#",
    "Open",
    "Answered",
    "Replied",
    "Closed",
    "Customer Reply",
    "Type Here",
    "Image Upload",
    "Reply",
    "user image",
    "File",
    "Confirmation",
    "Are you want to close ticket?",
    "Confirm",
    "Fund History",
    "All Payment",
    "Complete Payment",
    "Pending Payment",
    "Cancel Payment",
    "Search",
    "Transaction ID",
    "Gateway",
    "Amount",
    "Charge",
    "Time",
    "Complete",
    "Cancel",
    "Transaction",
    "Search for Transaction ID",
    "Remark",
    "Remarks",
    "2 Step Security",
    "Two Factor Authenticator",
    "Disable Two Factor Authenticator",
    "Enable Two Factor Authenticator",
    "Google Authenticator",
    "Use Google Authenticator to Scan the QR code  or use the code",
    "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, ▶",
    "DOWNLOAD APP",
    "Verify Your OTP",
    "Enter Google Authenticator Code",
    "Close",
    "Verify",
    "Verify Your OTP to Disable",
    "Added At",
    "Delete Confirmation",
    "Are you sure to delete this?",
    "Yes",
    "purchase plan image",
    "Transaction Limit:",
    "Payment By",
    "Payable",
    "Conversion Rate",
    "Purchase Product",
    "loader...",
    "Verification",
    "verification image",
    "Total Booking",
    "dashboard image",
    "Purchase Item",
    "My Favourites",
    "Last 5 Payments",
    "Last 5 Booking",
    "Blog Details",
    "Blog Details Image",
    "Share this blog post :",
    "Recent Posts",
    "Location",
    "Info",
    "Full Name",
    "Email",
    "Send Message",
    "product image",
    "Shop Photo",
    "Sorry! No item available for Shop at this moment",
    "Share : ",
    "CATEGORY : ",
    "Guaranteed Checkout",
    "Description",
    "Review",
    "Enter Feedback",
    "User's name here",
    "Related Product",
    "Photo",
    "Booking Request Form Not Submitted.",
    "Note",
];
